[project]
site_name = "Zensical Demo"
site_description = "A demonstration site built with Zensical"
site_author = "Ruud H."
copyright = """
Copyright © 2026 Ruud
"""

# Optional explicit navigation
nav = [
  { "Home" = "index.md" },
  { "Getting Started" = "getting-started.md" },
  { "Features" = "features.md" },
  { "Demo Components" = "components.md" }
]
