[project]
site_name = "Zensical Demo"
site_description = "A demonstration site built with Zensical"
site_author = "Ruud Hirschmann"
copyright = """
Copyright © 2026 Ruud Hirschmann
"""

[project.theme]
variant = "classic"


# Optional explicit navigation
nav = [
	{ "Welcome" = "index.md" },
	{ "Getting started" = "getting-started/index.md" },
	{ "Features" = "features/index.md" },
	{ "About" = [
			{ "Overview" = "about/index.md" },
			{ "Code of Conduct" = "code-of-conduct.md" },
			{ "Contributing to Zensical Demo" = "contributing.md" }
		] },
	{ "Changelog" = "changelog.md" }
]

[project.markdown]
# Enable Markdown extensions
extensions = [
	"admonition",
	"footnotes",
	"tables",
	"codehilite",
	"toc",
]

[project.navigation]
# Enable navigation features
path = true
footer = true

[project.navigation.instant]
# Instant navigation settings
enabled = true
prefetch = true
